// Contenido multiidioma del hub Invertir en Paraguay.
// Fuente única de verdad (capa config). Generado desde las traducciones de la rama i18n.
// Locales alineados con lib/i18n.ts + alemán (de).

export type InvertirLocale = "es" | "en" | "pt-br" | "de";

export const INVERTIR_I18N = {
  "es": {
    "meta": {
      "title": "Invertir en Paraguay 2026: energía, agroindustria y logística | AYCweb",
      "description": "Grado de inversión (Moody's y S&P), energía >99% renovable con excedente y corredor bioceánico en marcha. Dossier por sector y conexión con operadores locales en Paraguay.",
      "ogTitle": "Invertir en Paraguay: la tesis, los datos y la red local",
      "ogDescription": "Energía >99% renovable, grado de inversión y corredor bioceánico. Inteligencia de inversión firmada por AYCweb."
    },
    "wa": {
      "dossier": "Hola, vengo de la página Invertir en Paraguay (aycweb.com/invertir-en-paraguay). Mi sector de interés es ___. Quiero recibir el dossier.",
      "call": "Hola Oscar, vengo de aycweb.com/invertir-en-paraguay y quiero agendar la llamada estratégica de 30 minutos."
    },
    "hero": {
      "badge": "AYCweb · Inteligencia de inversión · Paraguay 2026",
      "title": "Invertir en Paraguay:",
      "titleHighlight": "la tesis, los datos y la red local para ejecutarla",
      "subtitle": "Energía >99% renovable con excedente estructural, grado de inversión con dos calificadoras y un corredor bioceánico que se inaugura este año. Te damos el mapa verificado — y te conectamos con operadores industriales, logísticos y profesionales que ya trabajan en el país.",
      "ctaPrimary": "Recibir dossier por sector →",
      "ctaWhatsapp": "Hablar por WhatsApp",
      "noCost": "Sin costo. Sin spam. Respondemos en 24 h hábiles.",
      "sourceLabel": "Fuente: {src}",
      "stat1Label": "Generación renovable",
      "stat2Label": "Capacidad instalada",
      "stat3Label": "Grado de inversión",
      "stat4Label": "Puente bioceánico PY–BR"
    },
    "thesis": {
      "kicker": "Cinco ejes, un mismo motor",
      "body": "Paraguay genera más electricidad de la que consume y la cede a precio de descarte: en 2025 usó 25.768 GWh de los 36.439 GWh que le correspondían en Itaipú, y cedió el resto a ~US$ 15,7 por MWh cuando el precio regional ronda los US$ 100. <strong>Cada eje de esta tesis es una forma distinta de capturar esa brecha.</strong>",
      "source": "Fuente: abc.com.py (ene-2026, ago-2025) · Datos verificados al 10-06-2026"
    },
    "axes": {
      "requestDossier": "Pedir dossier de {sector}",
      "noCostBadge": "Sin costo · Datos verificados",
      "energia": {
        "kicker": "Eje 1 · Energía + Industrialización",
        "sectorName": "Energía + Industrialización",
        "title": "Energía que sobra, industria que falta",
        "body": "8.760 MW de capacidad instalada contra un pico de demanda de ~5.000 MW. Generación >99,9% renovable y un mercado eléctrico recién abierto a privados (Decreto 6034/2026, licitaciones previstas de 800 MW/año). El destino natural del excedente: data centers, industrias electrointensivas, hidrógeno y manufactura descarbonizada.",
        "item1": "Data centers y cómputo de alto consumo",
        "item2": "Electrointensivas (acero, aluminio, fertilizantes)",
        "item3": "Hidrógeno verde y derivados",
        "item4": "Manufactura para reshoring regional"
      },
      "agroindustria": {
        "kicker": "Eje 2 · Agroindustria",
        "sectorName": "Agroindustria",
        "title": "No vender granos: procesarlos",
        "body": "Cada kilo transformado multiplica el valor exportable. Proteínas vegetales, balanceados, aceites premium y biocombustibles — con energía barata como insumo estructural que ningún competidor regional puede replicar.",
        "item1": "Procesamiento de soja y oleaginosas",
        "item2": "Plantas de balanceados y proteína vegetal",
        "item3": "Genética animal y frío industrial",
        "item4": "Biocombustibles y exportación premium"
      },
      "tecnologia": {
        "kicker": "Eje 3 · Tecnología + Infraestructura Digital",
        "sectorName": "Tecnología + Infraestructura Digital",
        "title": "El país está subdigitalizado — y eso es la oportunidad",
        "body": "La mayoría de las empresas paraguayas opera ventas en Excel y WhatsApp manual. El retorno marginal de cada guaraní invertido en digitalización comercial es alto precisamente por eso. Es el eje donde AYCweb opera todos los días.",
        "item1": "SaaS B2B para industria y salud",
        "item2": "Fintech y automatización de pagos",
        "item3": "IA aplicada a logística y producción",
        "item4": "Motores cotizadores y CRM a medida"
      },
      "logistica": {
        "kicker": "Eje 4 · Logística + Corredor Bioceánico",
        "sectorName": "Logística + Corredor Bioceánico",
        "title": "El atajo de 8.000 km se abre este año",
        "body": "El puente Carmelo Peralta–Puerto Murtinho (~1.294 m) une sus extremos en junio de 2026 y el Corredor Bioceánico de Capricornio (~2.000 km) apunta a inaugurarse en el segundo semestre. Para cargas hacia Asia, recorta cerca de 8.000 km frente a las rutas atlánticas.",
        "item1": "Parques logísticos y puertos secos",
        "item2": "Almacenamiento en frío sobre el corredor",
        "item3": "Transporte y servicios al corredor",
        "item4": "Chaco: de periferia a nodo"
      },
      "realEstate": {
        "kicker": "Eje 5 · Real Estate Productivo",
        "sectorName": "Real Estate Productivo",
        "title": "No residencial: productivo",
        "body": "Galpones, depósitos, parques industriales y centros de distribución — la infraestructura física que los otros cuatro ejes van a demandar. El régimen de maquila (tributo único del 1% sobre valor agregado en territorio nacional) hace que cada metro cuadrado industrial tenga un inquilino natural.",
        "item1": "Galpones para maquila (tributo 1%)",
        "item2": "Parques industriales y zonas francas",
        "item3": "Depósitos sobre el corredor bioceánico",
        "item4": "Build-to-suit para industria y logística"
      }
    },
    "steps": {
      "kicker": "Del dato a la operación",
      "title": "3 pasos del mapa al terreno",
      "step1Title": "Pedís el dossier de tu sector",
      "step1Desc": "Documento con datos verificados y sus fuentes, marco regulatorio introductorio y mapa de actores. Sin costo.",
      "step2Title": "Llamada estratégica de 30 minutos",
      "step2Desc": "Entendemos objetivo, capital y horizonte. Te decimos con honestidad si Paraguay encaja con tu plan.",
      "step3Title": "Conexión y aterrizaje",
      "step3Desc": "Introducciones con operadores locales verificados y la infraestructura digital de tu operación — construida por AYCweb.",
      "note": "Las introducciones iniciales no tienen costo. El acompañamiento y la infraestructura digital se cotizan por alcance de proyecto."
    },
    "who": {
      "kicker": "Una firma que opera, no solo informa",
      "title": "¿Quién está detrás de este hub?",
      "p1": "<strong>AYCweb</strong> es una firma de infraestructura digital B2B con base en Asunción, fundada y operada por <strong>Oscar Amarilla</strong>. Antes de escribir código, Oscar operó logística, manufactura y compras. Hoy AYCweb construye los sistemas comerciales de empresas industriales y de salud en Paraguay: motores cotizadores, automatización de ventas y paneles operativos.",
      "p2": "Esta página existe porque la pregunta que más recibimos de afuera es la misma: <em>\"¿con quién hablo en Paraguay?\"</em>. Ahora tiene respuesta.",
      "whatsappLabel": "WhatsApp directo",
      "emailLabel": "Email",
      "rucLabel": "RUC"
    },
    "faq": {
      "kicker": "Preguntas frecuentes",
      "title": "Lo que todo inversor debería saber antes de llamar",
      "q1": "¿Esto es asesoramiento financiero o una oferta de inversión?",
      "a1": "No. Es inteligencia comercial y conexión con operadores. No vendemos valores, no gestionamos fondos de terceros ni recomendamos instrumentos.",
      "q2": "¿Qué incluye el dossier?",
      "a2": "Datos verificados con sus fuentes, marco regulatorio introductorio, costos de referencia y mapa de actores del sector elegido.",
      "q3": "¿Trabajan con inversores y empresas del exterior?",
      "a3": "Sí. Te orientamos sobre los pasos de constitución, banca y operación local, y sobre los profesionales que vas a necesitar en cada etapa.",
      "q4": "¿Cuánto cuesta?",
      "a4": "El dossier y la primera llamada, nada. Acompañamiento, representación e infraestructura digital se cotizan por alcance.",
      "q5": "¿Por qué AYCweb y no una consultora tradicional?",
      "a5": "Porque operamos en el terreno: construimos los sistemas comerciales de empresas paraguayas reales y venimos del lado operativo — logística, manufactura, compras — no solo del informe."
    },
    "form": {
      "kicker": "Acceso sin costo",
      "title": "Pedí tu dossier y agendá la llamada",
      "subtitle": "Completá el formulario. En 24 h hábiles te enviamos el dossier de tu sector y coordinamos la llamada estratégica de 30 minutos.",
      "successTitle": "¡Recibimos tu solicitud!",
      "successBody": "En 24 h hábiles nos ponemos en contacto. Podés también enviarnos el resumen directamente por WhatsApp:",
      "successCta": "Enviar resumen por WhatsApp →",
      "errorInvalid": "Datos inválidos. Revisá el formulario.",
      "name": "Nombre *",
      "namePlaceholder": "Tu nombre",
      "company": "Empresa (opcional)",
      "companyPlaceholder": "Tu empresa",
      "email": "Email *",
      "emailPlaceholder": "correo@empresa.com",
      "whatsapp": "WhatsApp *",
      "whatsappPlaceholder": "+54 9 11 1234-5678",
      "country": "País *",
      "countryPlaceholder": "Argentina, Brasil, España...",
      "sectorLabel": "Sector de interés *",
      "sectorPlaceholder": "Seleccioná un sector",
      "sectorEnergia": "Energía e industrialización",
      "sectorAgro": "Agroindustria",
      "sectorTec": "Tecnología e infraestructura digital",
      "sectorLog": "Logística y corredor bioceánico",
      "sectorRealEstate": "Real Estate productivo",
      "sectorOtro": "Otro / Explorar",
      "objectiveLabel": "Objetivo *",
      "objectivePlaceholder": "¿Qué buscás?",
      "objInvertir": "Invertir capital",
      "objInstalar": "Instalar una operación",
      "objSocio": "Encontrar socio local",
      "objExportar": "Exportar / importar",
      "objExplorar": "Explorar opciones",
      "capitalLabel": "Rango de capital *",
      "capitalPlaceholder": "Seleccioná un rango",
      "capital1": "Menos de US$ 50.000",
      "capital2": "US$ 50.000 – 250.000",
      "capital3": "US$ 250.000 – 1.000.000",
      "capital4": "Más de US$ 1.000.000",
      "capital5": "Prefiero no decirlo",
      "horizonLabel": "Horizonte de decisión *",
      "horizonPlaceholder": "¿En cuánto tiempo decidís?",
      "horizon1": "0 – 6 meses",
      "horizon2": "6 – 18 meses",
      "horizon3": "Más de 18 meses",
      "messageLabel": "Mensaje adicional (opcional)",
      "messagePlaceholder": "Contexto adicional, preguntas específicas, tamaño del proyecto...",
      "submit": "Solicitar dossier y llamada estratégica →",
      "submitting": "Enviando...",
      "footnote": "Sin costo. Sin spam. Respondemos en 24 h hábiles."
    },
    "disclaimer": {
      "title": "Aviso legal · Datos al 10-06-2026",
      "body": "La información de esta página tiene fines educativos y estratégicos. No constituye asesoramiento financiero, legal ni tributario; no es una oferta pública de valores ni una recomendación personalizada de inversión. AYCweb no intermedia valores ni administra fondos de terceros. Toda decisión de inversión requiere verificación independiente y asesoría profesional propia. Cada cifra se acompaña de su fuente; los valores pueden variar con el tiempo."
    },
    "calc": {
      "kicker": "Calculadora de arbitraje energético",
      "title": "¿Cuánto vale operar con tarifa paraguaya?",
      "consumption": "Consumo mensual (kWh)",
      "compareAgainst": "Comparar contra",
      "advantageTitle": "Ventaja Paraguay",
      "advantageBody": "A este consumo, Paraguay muestra una ventaja estimada de <strong>{pct}%</strong> frente a la referencia seleccionada.",
      "pyMonth": "Paraguay/mes",
      "refMonth": "Referencia/mes",
      "monthlyAdvantage": "Ventaja mensual",
      "annualAdvantage": "Ventaja anual estimada",
      "cta": "Solicitar diagnóstico energético →",
      "bmWorldBusiness": "Promedio mundial empresarial",
      "bmWorldResidential": "Promedio mundial residencial",
      "bmSouthAmericaBusiness": "Promedio Sudamérica empresarial",
      "bmEuropeBusiness": "Promedio Europa empresarial",
      "bmUsaBusiness": "Estados Unidos empresarial",
      "bmGermanyBusiness": "Alemania empresarial",
      "bmBrazilBusiness": "Brasil empresarial",
      "bmUruguayBusiness": "Uruguay empresarial"
    }
  },
  "en": {
    "meta": {
      "title": "Investing in Paraguay 2026: energy, agribusiness & logistics | AYCweb",
      "description": "Investment grade (Moody's and S&P), >99% renewable energy with structural surplus and a bioceanic corridor underway. Sector dossiers and connections with local operators in Paraguay.",
      "ogTitle": "Investing in Paraguay: the thesis, the data and the local network",
      "ogDescription": ">99% renewable energy, investment grade and a bioceanic corridor. Investment intelligence signed by AYCweb."
    },
    "wa": {
      "dossier": "Hi, I'm coming from the Investing in Paraguay page (aycweb.com/invertir-en-paraguay). My sector of interest is ___. I'd like to receive the dossier.",
      "call": "Hi Oscar, I'm coming from aycweb.com/invertir-en-paraguay and I'd like to book the 30-minute strategy call."
    },
    "hero": {
      "badge": "AYCweb · Investment intelligence · Paraguay 2026",
      "title": "Investing in Paraguay:",
      "titleHighlight": "the thesis, the data and the local network to execute it",
      "subtitle": ">99% renewable energy with a structural surplus, investment grade from two rating agencies and a bioceanic corridor opening this year. We give you the verified map — and connect you with industrial, logistics and professional operators already working in the country.",
      "ctaPrimary": "Get the sector dossier →",
      "ctaWhatsapp": "Talk on WhatsApp",
      "noCost": "Free. No spam. We reply within 24 business hours.",
      "sourceLabel": "Source: {src}",
      "stat1Label": "Renewable generation",
      "stat2Label": "Installed capacity",
      "stat3Label": "Investment grade",
      "stat4Label": "PY–BR bioceanic bridge"
    },
    "thesis": {
      "kicker": "Five axes, one engine",
      "body": "Paraguay generates more electricity than it consumes and gives the surplus away at scrap prices: in 2025 it used 25,768 GWh of the 36,439 GWh it was entitled to from Itaipú, ceding the rest at ~US$ 15.7 per MWh while the regional price hovers around US$ 100. <strong>Each axis of this thesis is a different way to capture that gap.</strong>",
      "source": "Source: abc.com.py (Jan 2026, Aug 2025) · Data verified as of 06-10-2026"
    },
    "axes": {
      "requestDossier": "Request the {sector} dossier",
      "noCostBadge": "Free · Verified data",
      "energia": {
        "kicker": "Axis 1 · Energy + Industrialization",
        "sectorName": "Energy + Industrialization",
        "title": "Surplus energy, missing industry",
        "body": "8,760 MW of installed capacity against a peak demand of ~5,000 MW. Generation >99.9% renewable and an electricity market just opened to private players (Decree 6034/2026, planned tenders of 800 MW/year). The natural destination for the surplus: data centers, electro-intensive industries, hydrogen and decarbonized manufacturing.",
        "item1": "Data centers and high-consumption computing",
        "item2": "Electro-intensive industries (steel, aluminum, fertilizers)",
        "item3": "Green hydrogen and derivatives",
        "item4": "Manufacturing for regional reshoring"
      },
      "agroindustria": {
        "kicker": "Axis 2 · Agribusiness",
        "sectorName": "Agribusiness",
        "title": "Don't sell grain: process it",
        "body": "Every processed kilo multiplies export value. Plant proteins, animal feed, premium oils and biofuels — with cheap energy as a structural input no regional competitor can replicate.",
        "item1": "Soy and oilseed processing",
        "item2": "Feed and plant-protein plants",
        "item3": "Animal genetics and industrial cold chain",
        "item4": "Biofuels and premium exports"
      },
      "tecnologia": {
        "kicker": "Axis 3 · Technology + Digital Infrastructure",
        "sectorName": "Technology + Digital Infrastructure",
        "title": "The country is under-digitalized — and that's the opportunity",
        "body": "Most Paraguayan companies run sales on Excel and manual WhatsApp. The marginal return of every guaraní invested in commercial digitalization is high precisely because of that. It's the axis where AYCweb operates every day.",
        "item1": "B2B SaaS for industry and healthcare",
        "item2": "Fintech and payment automation",
        "item3": "AI applied to logistics and production",
        "item4": "Custom quoting engines and CRMs"
      },
      "logistica": {
        "kicker": "Axis 4 · Logistics + Bioceanic Corridor",
        "sectorName": "Logistics + Bioceanic Corridor",
        "title": "The 8,000 km shortcut opens this year",
        "body": "The Carmelo Peralta–Puerto Murtinho bridge (~1,294 m) joins its two ends in June 2026 and the Capricorn Bioceanic Corridor (~2,000 km) aims to open in the second half of the year. For cargo headed to Asia, it cuts roughly 8,000 km versus Atlantic routes.",
        "item1": "Logistics parks and dry ports",
        "item2": "Cold storage along the corridor",
        "item3": "Transport and corridor services",
        "item4": "Chaco: from periphery to node"
      },
      "realEstate": {
        "kicker": "Axis 5 · Productive Real Estate",
        "sectorName": "Productive Real Estate",
        "title": "Not residential: productive",
        "body": "Warehouses, depots, industrial parks and distribution centers — the physical infrastructure the other four axes will demand. The maquila regime (a single 1% tax on value added within the country) gives every industrial square meter a natural tenant.",
        "item1": "Warehouses for maquila (1% tax)",
        "item2": "Industrial parks and free-trade zones",
        "item3": "Depots along the bioceanic corridor",
        "item4": "Build-to-suit for industry and logistics"
      }
    },
    "steps": {
      "kicker": "From data to operation",
      "title": "3 steps from the map to the ground",
      "step1Title": "You request your sector's dossier",
      "step1Desc": "A document with verified data and its sources, an introductory regulatory framework and a map of key players. Free of charge.",
      "step2Title": "30-minute strategy call",
      "step2Desc": "We understand your objective, capital and timeline. We'll tell you honestly whether Paraguay fits your plan.",
      "step3Title": "Connection and landing",
      "step3Desc": "Introductions to verified local operators and the digital infrastructure for your operation — built by AYCweb.",
      "note": "Initial introductions are free. Ongoing support and digital infrastructure are quoted per project scope."
    },
    "who": {
      "kicker": "A firm that operates, not just reports",
      "title": "Who is behind this hub?",
      "p1": "<strong>AYCweb</strong> is a B2B digital infrastructure firm based in Asunción, founded and run by <strong>Oscar Amarilla</strong>. Before writing code, Oscar worked in logistics, manufacturing and procurement. Today AYCweb builds the commercial systems of industrial and healthcare companies in Paraguay: quoting engines, sales automation and operational dashboards.",
      "p2": "This page exists because the question we get most from abroad is always the same: <em>\"who do I talk to in Paraguay?\"</em>. Now it has an answer.",
      "whatsappLabel": "Direct WhatsApp",
      "emailLabel": "Email",
      "rucLabel": "Tax ID (RUC)"
    },
    "faq": {
      "kicker": "Frequently asked questions",
      "title": "What every investor should know before calling",
      "q1": "Is this financial advice or an investment offer?",
      "a1": "No. It's commercial intelligence and connections with operators. We don't sell securities, manage third-party funds or recommend instruments.",
      "q2": "What does the dossier include?",
      "a2": "Verified data with sources, an introductory regulatory framework, reference costs and a map of key players in your chosen sector.",
      "q3": "Do you work with foreign investors and companies?",
      "a3": "Yes. We guide you through incorporation, banking and local operations, and point you to the professionals you'll need at each stage.",
      "q4": "How much does it cost?",
      "a4": "The dossier and the first call: nothing. Ongoing support, representation and digital infrastructure are quoted per scope.",
      "q5": "Why AYCweb and not a traditional consultancy?",
      "a5": "Because we operate on the ground: we build the commercial systems of real Paraguayan companies and come from the operational side — logistics, manufacturing, procurement — not just from reports."
    },
    "form": {
      "kicker": "Free access",
      "title": "Request your dossier and book the call",
      "subtitle": "Fill in the form. Within 24 business hours we'll send your sector's dossier and schedule the 30-minute strategy call.",
      "successTitle": "We received your request!",
      "successBody": "We'll get in touch within 24 business hours. You can also send us the summary directly on WhatsApp:",
      "successCta": "Send summary on WhatsApp →",
      "errorInvalid": "Invalid data. Please review the form.",
      "name": "Name *",
      "namePlaceholder": "Your name",
      "company": "Company (optional)",
      "companyPlaceholder": "Your company",
      "email": "Email *",
      "emailPlaceholder": "you@company.com",
      "whatsapp": "WhatsApp *",
      "whatsappPlaceholder": "+1 555 123 4567",
      "country": "Country *",
      "countryPlaceholder": "USA, Germany, Brazil...",
      "sectorLabel": "Sector of interest *",
      "sectorPlaceholder": "Select a sector",
      "sectorEnergia": "Energy and industrialization",
      "sectorAgro": "Agribusiness",
      "sectorTec": "Technology and digital infrastructure",
      "sectorLog": "Logistics and bioceanic corridor",
      "sectorRealEstate": "Productive real estate",
      "sectorOtro": "Other / Exploring",
      "objectiveLabel": "Objective *",
      "objectivePlaceholder": "What are you looking for?",
      "objInvertir": "Invest capital",
      "objInstalar": "Set up an operation",
      "objSocio": "Find a local partner",
      "objExportar": "Export / import",
      "objExplorar": "Explore options",
      "capitalLabel": "Capital range *",
      "capitalPlaceholder": "Select a range",
      "capital1": "Under US$ 50,000",
      "capital2": "US$ 50,000 – 250,000",
      "capital3": "US$ 250,000 – 1,000,000",
      "capital4": "Over US$ 1,000,000",
      "capital5": "Prefer not to say",
      "horizonLabel": "Decision timeline *",
      "horizonPlaceholder": "How soon will you decide?",
      "horizon1": "0 – 6 months",
      "horizon2": "6 – 18 months",
      "horizon3": "Over 18 months",
      "messageLabel": "Additional message (optional)",
      "messagePlaceholder": "Extra context, specific questions, project size...",
      "submit": "Request dossier and strategy call →",
      "submitting": "Sending...",
      "footnote": "Free. No spam. We reply within 24 business hours."
    },
    "disclaimer": {
      "title": "Legal notice · Data as of 06-10-2026",
      "body": "The information on this page is for educational and strategic purposes. It does not constitute financial, legal or tax advice; it is not a public offering of securities nor a personalized investment recommendation. AYCweb does not broker securities or manage third-party funds. Every investment decision requires independent verification and your own professional advice. Each figure is accompanied by its source; values may change over time."
    },
    "calc": {
      "kicker": "Energy arbitrage calculator",
      "title": "What is operating on Paraguayan tariffs worth?",
      "consumption": "Monthly consumption (kWh)",
      "compareAgainst": "Compare against",
      "advantageTitle": "Paraguay advantage",
      "advantageBody": "At this consumption level, Paraguay shows an estimated advantage of <strong>{pct}%</strong> versus the selected benchmark.",
      "pyMonth": "Paraguay/month",
      "refMonth": "Benchmark/month",
      "monthlyAdvantage": "Monthly advantage",
      "annualAdvantage": "Estimated annual advantage",
      "cta": "Request an energy assessment →",
      "bmWorldBusiness": "World business average",
      "bmWorldResidential": "World residential average",
      "bmSouthAmericaBusiness": "South America business average",
      "bmEuropeBusiness": "Europe business average",
      "bmUsaBusiness": "United States business",
      "bmGermanyBusiness": "Germany business",
      "bmBrazilBusiness": "Brazil business",
      "bmUruguayBusiness": "Uruguay business"
    }
  },
  "pt-br": {
    "meta": {
      "title": "Investir no Paraguai 2026: energia, agroindústria e logística | AYCweb",
      "description": "Grau de investimento (Moody's e S&P), energia >99% renovável com excedente e corredor bioceânico em andamento. Dossiê por setor e conexão com operadores locais no Paraguai.",
      "ogTitle": "Investir no Paraguai: a tese, os dados e a rede local",
      "ogDescription": "Energia >99% renovável, grau de investimento e corredor bioceânico. Inteligência de investimento assinada pela AYCweb."
    },
    "wa": {
      "dossier": "Olá, venho da página Investir no Paraguai (aycweb.com/invertir-en-paraguay). Meu setor de interesse é ___. Quero receber o dossiê.",
      "call": "Olá Oscar, venho de aycweb.com/invertir-en-paraguay e quero agendar a chamada estratégica de 30 minutos."
    },
    "hero": {
      "badge": "AYCweb · Inteligência de investimento · Paraguai 2026",
      "title": "Investir no Paraguai:",
      "titleHighlight": "a tese, os dados e a rede local para executá-la",
      "subtitle": "Energia >99% renovável com excedente estrutural, grau de investimento por duas agências e um corredor bioceânico que inaugura este ano. Entregamos o mapa verificado — e conectamos você com operadores industriais, logísticos e profissionais que já trabalham no país.",
      "ctaPrimary": "Receber dossiê por setor →",
      "ctaWhatsapp": "Falar no WhatsApp",
      "noCost": "Sem custo. Sem spam. Respondemos em 24 h úteis.",
      "sourceLabel": "Fonte: {src}",
      "stat1Label": "Geração renovável",
      "stat2Label": "Capacidade instalada",
      "stat3Label": "Grau de investimento",
      "stat4Label": "Ponte bioceânica PY–BR"
    },
    "thesis": {
      "kicker": "Cinco eixos, um mesmo motor",
      "body": "O Paraguai gera mais eletricidade do que consome e cede o excedente a preço de descarte: em 2025 usou 25.768 GWh dos 36.439 GWh a que tinha direito em Itaipu, cedendo o resto a ~US$ 15,7 por MWh enquanto o preço regional gira em torno de US$ 100. <strong>Cada eixo desta tese é uma forma diferente de capturar essa diferença.</strong>",
      "source": "Fonte: abc.com.py (jan-2026, ago-2025) · Dados verificados em 10-06-2026"
    },
    "axes": {
      "requestDossier": "Pedir dossiê de {sector}",
      "noCostBadge": "Sem custo · Dados verificados",
      "energia": {
        "kicker": "Eixo 1 · Energia + Industrialização",
        "sectorName": "Energia + Industrialização",
        "title": "Energia que sobra, indústria que falta",
        "body": "8.760 MW de capacidade instalada contra um pico de demanda de ~5.000 MW. Geração >99,9% renovável e um mercado elétrico recém-aberto a privados (Decreto 6034/2026, leilões previstos de 800 MW/ano). O destino natural do excedente: data centers, indústrias eletrointensivas, hidrogênio e manufatura descarbonizada.",
        "item1": "Data centers e computação de alto consumo",
        "item2": "Eletrointensivas (aço, alumínio, fertilizantes)",
        "item3": "Hidrogênio verde e derivados",
        "item4": "Manufatura para reshoring regional"
      },
      "agroindustria": {
        "kicker": "Eixo 2 · Agroindústria",
        "sectorName": "Agroindústria",
        "title": "Não vender grãos: processá-los",
        "body": "Cada quilo transformado multiplica o valor exportável. Proteínas vegetais, ração, óleos premium e biocombustíveis — com energia barata como insumo estrutural que nenhum concorrente regional consegue replicar.",
        "item1": "Processamento de soja e oleaginosas",
        "item2": "Plantas de ração e proteína vegetal",
        "item3": "Genética animal e frio industrial",
        "item4": "Biocombustíveis e exportação premium"
      },
      "tecnologia": {
        "kicker": "Eixo 3 · Tecnologia + Infraestrutura Digital",
        "sectorName": "Tecnologia + Infraestrutura Digital",
        "title": "O país é subdigitalizado — e essa é a oportunidade",
        "body": "A maioria das empresas paraguaias opera vendas no Excel e WhatsApp manual. O retorno marginal de cada guarani investido em digitalização comercial é alto justamente por isso. É o eixo onde a AYCweb opera todos os dias.",
        "item1": "SaaS B2B para indústria e saúde",
        "item2": "Fintech e automação de pagamentos",
        "item3": "IA aplicada à logística e produção",
        "item4": "Motores de cotação e CRM sob medida"
      },
      "logistica": {
        "kicker": "Eixo 4 · Logística + Corredor Bioceânico",
        "sectorName": "Logística + Corredor Bioceânico",
        "title": "O atalho de 8.000 km abre este ano",
        "body": "A ponte Carmelo Peralta–Porto Murtinho (~1.294 m) une suas extremidades em junho de 2026 e o Corredor Bioceânico de Capricórnio (~2.000 km) deve inaugurar no segundo semestre. Para cargas rumo à Ásia, corta cerca de 8.000 km em relação às rotas atlânticas.",
        "item1": "Parques logísticos e portos secos",
        "item2": "Armazenagem refrigerada ao longo do corredor",
        "item3": "Transporte e serviços ao corredor",
        "item4": "Chaco: de periferia a nó logístico"
      },
      "realEstate": {
        "kicker": "Eixo 5 · Real Estate Produtivo",
        "sectorName": "Real Estate Produtivo",
        "title": "Não residencial: produtivo",
        "body": "Galpões, depósitos, parques industriais e centros de distribuição — a infraestrutura física que os outros quatro eixos vão demandar. O regime de maquila (tributo único de 1% sobre o valor agregado em território nacional) faz com que cada metro quadrado industrial tenha um inquilino natural.",
        "item1": "Galpões para maquila (tributo de 1%)",
        "item2": "Parques industriais e zonas francas",
        "item3": "Depósitos sobre o corredor bioceânico",
        "item4": "Build-to-suit para indústria e logística"
      }
    },
    "steps": {
      "kicker": "Do dado à operação",
      "title": "3 passos do mapa ao terreno",
      "step1Title": "Você pede o dossiê do seu setor",
      "step1Desc": "Documento com dados verificados e suas fontes, marco regulatório introdutório e mapa de atores. Sem custo.",
      "step2Title": "Chamada estratégica de 30 minutos",
      "step2Desc": "Entendemos objetivo, capital e horizonte. Falamos com honestidade se o Paraguai encaixa no seu plano.",
      "step3Title": "Conexão e aterrissagem",
      "step3Desc": "Apresentações a operadores locais verificados e a infraestrutura digital da sua operação — construída pela AYCweb.",
      "note": "As apresentações iniciais não têm custo. Acompanhamento e infraestrutura digital são cotados por escopo de projeto."
    },
    "who": {
      "kicker": "Uma firma que opera, não apenas informa",
      "title": "Quem está por trás deste hub?",
      "p1": "A <strong>AYCweb</strong> é uma firma de infraestrutura digital B2B com sede em Assunção, fundada e operada por <strong>Oscar Amarilla</strong>. Antes de escrever código, Oscar operou logística, manufatura e compras. Hoje a AYCweb constrói os sistemas comerciais de empresas industriais e de saúde no Paraguai: motores de cotação, automação de vendas e painéis operacionais.",
      "p2": "Esta página existe porque a pergunta que mais recebemos de fora é sempre a mesma: <em>\"com quem eu falo no Paraguai?\"</em>. Agora tem resposta.",
      "whatsappLabel": "WhatsApp direto",
      "emailLabel": "E-mail",
      "rucLabel": "RUC (CNPJ paraguaio)"
    },
    "faq": {
      "kicker": "Perguntas frequentes",
      "title": "O que todo investidor deveria saber antes de ligar",
      "q1": "Isto é assessoria financeira ou uma oferta de investimento?",
      "a1": "Não. É inteligência comercial e conexão com operadores. Não vendemos valores mobiliários, não gerimos fundos de terceiros nem recomendamos instrumentos.",
      "q2": "O que o dossiê inclui?",
      "a2": "Dados verificados com suas fontes, marco regulatório introdutório, custos de referência e mapa de atores do setor escolhido.",
      "q3": "Vocês trabalham com investidores e empresas do exterior?",
      "a3": "Sim. Orientamos sobre os passos de constituição, bancos e operação local, e sobre os profissionais que você vai precisar em cada etapa.",
      "q4": "Quanto custa?",
      "a4": "O dossiê e a primeira chamada, nada. Acompanhamento, representação e infraestrutura digital são cotados por escopo.",
      "q5": "Por que a AYCweb e não uma consultoria tradicional?",
      "a5": "Porque operamos no terreno: construímos os sistemas comerciais de empresas paraguaias reais e viemos do lado operacional — logística, manufatura, compras — não apenas do relatório."
    },
    "form": {
      "kicker": "Acesso sem custo",
      "title": "Peça seu dossiê e agende a chamada",
      "subtitle": "Preencha o formulário. Em 24 h úteis enviamos o dossiê do seu setor e coordenamos a chamada estratégica de 30 minutos.",
      "successTitle": "Recebemos sua solicitação!",
      "successBody": "Em 24 h úteis entramos em contato. Você também pode nos enviar o resumo diretamente pelo WhatsApp:",
      "successCta": "Enviar resumo pelo WhatsApp →",
      "errorInvalid": "Dados inválidos. Revise o formulário.",
      "name": "Nome *",
      "namePlaceholder": "Seu nome",
      "company": "Empresa (opcional)",
      "companyPlaceholder": "Sua empresa",
      "email": "E-mail *",
      "emailPlaceholder": "email@empresa.com",
      "whatsapp": "WhatsApp *",
      "whatsappPlaceholder": "+55 11 91234-5678",
      "country": "País *",
      "countryPlaceholder": "Brasil, Argentina, Portugal...",
      "sectorLabel": "Setor de interesse *",
      "sectorPlaceholder": "Selecione um setor",
      "sectorEnergia": "Energia e industrialização",
      "sectorAgro": "Agroindústria",
      "sectorTec": "Tecnologia e infraestrutura digital",
      "sectorLog": "Logística e corredor bioceânico",
      "sectorRealEstate": "Real estate produtivo",
      "sectorOtro": "Outro / Explorar",
      "objectiveLabel": "Objetivo *",
      "objectivePlaceholder": "O que você busca?",
      "objInvertir": "Investir capital",
      "objInstalar": "Instalar uma operação",
      "objSocio": "Encontrar sócio local",
      "objExportar": "Exportar / importar",
      "objExplorar": "Explorar opções",
      "capitalLabel": "Faixa de capital *",
      "capitalPlaceholder": "Selecione uma faixa",
      "capital1": "Menos de US$ 50.000",
      "capital2": "US$ 50.000 – 250.000",
      "capital3": "US$ 250.000 – 1.000.000",
      "capital4": "Mais de US$ 1.000.000",
      "capital5": "Prefiro não dizer",
      "horizonLabel": "Horizonte de decisão *",
      "horizonPlaceholder": "Em quanto tempo você decide?",
      "horizon1": "0 – 6 meses",
      "horizon2": "6 – 18 meses",
      "horizon3": "Mais de 18 meses",
      "messageLabel": "Mensagem adicional (opcional)",
      "messagePlaceholder": "Contexto adicional, perguntas específicas, tamanho do projeto...",
      "submit": "Solicitar dossiê e chamada estratégica →",
      "submitting": "Enviando...",
      "footnote": "Sem custo. Sem spam. Respondemos em 24 h úteis."
    },
    "disclaimer": {
      "title": "Aviso legal · Dados em 10-06-2026",
      "body": "As informações desta página têm fins educativos e estratégicos. Não constituem assessoria financeira, jurídica nem tributária; não são uma oferta pública de valores mobiliários nem uma recomendação personalizada de investimento. A AYCweb não intermedia valores nem administra fundos de terceiros. Toda decisão de investimento exige verificação independente e assessoria profissional própria. Cada número vem acompanhado de sua fonte; os valores podem variar com o tempo."
    },
    "calc": {
      "kicker": "Calculadora de arbitragem energética",
      "title": "Quanto vale operar com tarifa paraguaia?",
      "consumption": "Consumo mensal (kWh)",
      "compareAgainst": "Comparar com",
      "advantageTitle": "Vantagem Paraguai",
      "advantageBody": "Neste consumo, o Paraguai mostra uma vantagem estimada de <strong>{pct}%</strong> em relação à referência selecionada.",
      "pyMonth": "Paraguai/mês",
      "refMonth": "Referência/mês",
      "monthlyAdvantage": "Vantagem mensal",
      "annualAdvantage": "Vantagem anual estimada",
      "cta": "Solicitar diagnóstico energético →",
      "bmWorldBusiness": "Média mundial empresarial",
      "bmWorldResidential": "Média mundial residencial",
      "bmSouthAmericaBusiness": "Média América do Sul empresarial",
      "bmEuropeBusiness": "Média Europa empresarial",
      "bmUsaBusiness": "Estados Unidos empresarial",
      "bmGermanyBusiness": "Alemanha empresarial",
      "bmBrazilBusiness": "Brasil empresarial",
      "bmUruguayBusiness": "Uruguai empresarial"
    }
  },
  "de": {
    "meta": {
      "title": "In Paraguay investieren 2026: Energie, Agroindustrie & Logistik | AYCweb",
      "description": "Investment Grade (Moody's und S&P), >99 % erneuerbare Energie mit strukturellem Überschuss und ein bioozeanischer Korridor im Bau. Sektor-Dossiers und Kontakte zu lokalen Betreibern in Paraguay.",
      "ogTitle": "In Paraguay investieren: die These, die Daten und das lokale Netzwerk",
      "ogDescription": ">99 % erneuerbare Energie, Investment Grade und ein bioozeanischer Korridor. Investment-Intelligenz von AYCweb."
    },
    "wa": {
      "dossier": "Hi, I'm coming from the Investing in Paraguay page (aycweb.com/invertir-en-paraguay). My sector of interest is ___. I'd like to receive the dossier.",
      "call": "Hi Oscar, I'm coming from aycweb.com/invertir-en-paraguay and I'd like to book the 30-minute strategy call."
    },
    "hero": {
      "badge": "AYCweb · Investment-Intelligenz · Paraguay 2026",
      "title": "In Paraguay investieren:",
      "titleHighlight": "die These, die Daten und das lokale Netzwerk zur Umsetzung",
      "subtitle": ">99 % erneuerbare Energie mit strukturellem Überschuss, Investment Grade von zwei Ratingagenturen und ein bioozeanischer Korridor, der dieses Jahr eröffnet wird. Wir geben Ihnen die verifizierte Landkarte — und verbinden Sie mit Industrie-, Logistik- und Fachbetreibern, die bereits im Land arbeiten.",
      "ctaPrimary": "Sektor-Dossier erhalten →",
      "ctaWhatsapp": "Per WhatsApp sprechen",
      "noCost": "Kostenlos. Kein Spam. Antwort innerhalb von 24 Geschäftsstunden.",
      "sourceLabel": "Quelle: {src}",
      "stat1Label": "Erneuerbare Erzeugung",
      "stat2Label": "Installierte Kapazität",
      "stat3Label": "Investment Grade",
      "stat4Label": "Bioozeanische Brücke PY–BR"
    },
    "thesis": {
      "kicker": "Fünf Achsen, ein Motor",
      "body": "Paraguay erzeugt mehr Strom, als es verbraucht, und gibt den Überschuss zu Schleuderpreisen ab: 2025 nutzte es 25.768 GWh der 36.439 GWh, die ihm aus Itaipú zustanden, und trat den Rest zu ~15,7 US$ pro MWh ab, während der regionale Preis um die 100 US$ liegt. <strong>Jede Achse dieser These ist ein anderer Weg, diese Lücke zu nutzen.</strong>",
      "source": "Quelle: abc.com.py (Jan. 2026, Aug. 2025) · Daten geprüft am 10.06.2026"
    },
    "axes": {
      "requestDossier": "Dossier {sector} anfordern",
      "noCostBadge": "Kostenlos · Geprüfte Daten",
      "energia": {
        "kicker": "Achse 1 · Energie + Industrialisierung",
        "sectorName": "Energie + Industrialisierung",
        "title": "Energie im Überfluss, Industrie im Rückstand",
        "body": "8.760 MW installierte Kapazität gegenüber einer Spitzenlast von ~5.000 MW. Erzeugung zu >99,9 % erneuerbar und ein Strommarkt, der gerade für Private geöffnet wurde (Dekret 6034/2026, geplante Ausschreibungen von 800 MW/Jahr). Das natürliche Ziel des Überschusses: Rechenzentren, energieintensive Industrien, Wasserstoff und dekarbonisierte Fertigung.",
        "item1": "Rechenzentren und energieintensives Computing",
        "item2": "Energieintensive Industrien (Stahl, Aluminium, Dünger)",
        "item3": "Grüner Wasserstoff und Derivate",
        "item4": "Fertigung für regionales Reshoring"
      },
      "agroindustria": {
        "kicker": "Achse 2 · Agroindustrie",
        "sectorName": "Agroindustrie",
        "title": "Getreide nicht verkaufen: verarbeiten",
        "body": "Jedes verarbeitete Kilo vervielfacht den Exportwert. Pflanzenproteine, Futtermittel, Premium-Öle und Biokraftstoffe — mit günstiger Energie als strukturellem Input, den kein regionaler Wettbewerber nachbilden kann.",
        "item1": "Verarbeitung von Soja und Ölsaaten",
        "item2": "Futtermittel- und Pflanzenproteinanlagen",
        "item3": "Tiergenetik und industrielle Kühlketten",
        "item4": "Biokraftstoffe und Premium-Exporte"
      },
      "tecnologia": {
        "kicker": "Achse 3 · Technologie + digitale Infrastruktur",
        "sectorName": "Technologie + digitale Infrastruktur",
        "title": "Das Land ist unterdigitalisiert — genau das ist die Chance",
        "body": "Die meisten paraguayischen Unternehmen wickeln ihren Vertrieb über Excel und manuelles WhatsApp ab. Die Grenzrendite jedes in kommerzielle Digitalisierung investierten Guaraní ist genau deshalb hoch. Es ist die Achse, auf der AYCweb täglich arbeitet.",
        "item1": "B2B-SaaS für Industrie und Gesundheitswesen",
        "item2": "Fintech und Zahlungsautomatisierung",
        "item3": "KI für Logistik und Produktion",
        "item4": "Maßgeschneiderte Angebots-Engines und CRMs"
      },
      "logistica": {
        "kicker": "Achse 4 · Logistik + bioozeanischer Korridor",
        "sectorName": "Logistik + bioozeanischer Korridor",
        "title": "Die 8.000-km-Abkürzung öffnet dieses Jahr",
        "body": "Die Brücke Carmelo Peralta–Puerto Murtinho (~1.294 m) wird im Juni 2026 geschlossen, und der bioozeanische Capricorn-Korridor (~2.000 km) soll in der zweiten Jahreshälfte eröffnet werden. Für Fracht nach Asien spart er rund 8.000 km gegenüber den Atlantikrouten.",
        "item1": "Logistikparks und Trockenhäfen",
        "item2": "Kühllager entlang des Korridors",
        "item3": "Transport und Dienstleistungen am Korridor",
        "item4": "Chaco: von der Peripherie zum Knotenpunkt"
      },
      "realEstate": {
        "kicker": "Achse 5 · Produktive Immobilien",
        "sectorName": "Produktive Immobilien",
        "title": "Nicht Wohnen: Produktion",
        "body": "Hallen, Lager, Industrieparks und Verteilzentren — die physische Infrastruktur, die die anderen vier Achsen nachfragen werden. Das Maquila-Regime (einheitliche Steuer von 1 % auf die im Land geschaffene Wertschöpfung) verschafft jedem industriellen Quadratmeter einen natürlichen Mieter.",
        "item1": "Hallen für Maquila (1 % Steuer)",
        "item2": "Industrieparks und Freihandelszonen",
        "item3": "Lager am bioozeanischen Korridor",
        "item4": "Build-to-suit für Industrie und Logistik"
      }
    },
    "steps": {
      "kicker": "Vom Datenpunkt zum Betrieb",
      "title": "3 Schritte von der Landkarte aufs Terrain",
      "step1Title": "Sie fordern das Dossier Ihres Sektors an",
      "step1Desc": "Dokument mit geprüften Daten und Quellen, einführendem Regulierungsrahmen und Akteurslandkarte. Kostenlos.",
      "step2Title": "30-minütiges Strategiegespräch",
      "step2Desc": "Wir verstehen Ziel, Kapital und Zeithorizont. Wir sagen Ihnen ehrlich, ob Paraguay zu Ihrem Plan passt.",
      "step3Title": "Vernetzung und Landung",
      "step3Desc": "Vorstellung bei geprüften lokalen Betreibern und die digitale Infrastruktur Ihres Betriebs — gebaut von AYCweb.",
      "note": "Die ersten Vorstellungen sind kostenlos. Begleitung und digitale Infrastruktur werden nach Projektumfang angeboten."
    },
    "who": {
      "kicker": "Eine Firma, die operiert — nicht nur berichtet",
      "title": "Wer steht hinter diesem Hub?",
      "p1": "<strong>AYCweb</strong> ist eine B2B-Firma für digitale Infrastruktur mit Sitz in Asunción, gegründet und geführt von <strong>Oscar Amarilla</strong>. Bevor er Code schrieb, arbeitete Oscar in Logistik, Fertigung und Einkauf. Heute baut AYCweb die Vertriebssysteme von Industrie- und Gesundheitsunternehmen in Paraguay: Angebots-Engines, Vertriebsautomatisierung und operative Dashboards.",
      "p2": "Diese Seite existiert, weil die häufigste Frage aus dem Ausland immer dieselbe ist: <em>„Mit wem spreche ich in Paraguay?“</em> Jetzt gibt es eine Antwort.",
      "whatsappLabel": "Direktes WhatsApp",
      "emailLabel": "E-Mail",
      "rucLabel": "Steuernummer (RUC)"
    },
    "faq": {
      "kicker": "Häufige Fragen",
      "title": "Was jeder Investor vor dem Anruf wissen sollte",
      "q1": "Ist das Finanzberatung oder ein Investitionsangebot?",
      "a1": "Nein. Es ist kommerzielle Intelligenz und Vernetzung mit Betreibern. Wir verkaufen keine Wertpapiere, verwalten keine Drittgelder und empfehlen keine Instrumente.",
      "q2": "Was enthält das Dossier?",
      "a2": "Geprüfte Daten mit Quellen, einen einführenden Regulierungsrahmen, Referenzkosten und eine Akteurslandkarte des gewählten Sektors.",
      "q3": "Arbeiten Sie mit Investoren und Unternehmen aus dem Ausland?",
      "a3": "Ja. Wir orientieren Sie zu Gründung, Bankgeschäften und lokalem Betrieb — und zu den Fachleuten, die Sie in jeder Phase brauchen.",
      "q4": "Was kostet das?",
      "a4": "Das Dossier und das erste Gespräch: nichts. Begleitung, Vertretung und digitale Infrastruktur werden nach Umfang angeboten.",
      "q5": "Warum AYCweb und nicht eine klassische Beratung?",
      "a5": "Weil wir vor Ort operieren: Wir bauen die Vertriebssysteme realer paraguayischer Unternehmen und kommen von der operativen Seite — Logistik, Fertigung, Einkauf — nicht nur vom Bericht."
    },
    "form": {
      "kicker": "Kostenloser Zugang",
      "title": "Fordern Sie Ihr Dossier an und buchen Sie das Gespräch",
      "subtitle": "Füllen Sie das Formular aus. Innerhalb von 24 Geschäftsstunden senden wir das Dossier Ihres Sektors und koordinieren das 30-minütige Strategiegespräch.",
      "successTitle": "Wir haben Ihre Anfrage erhalten!",
      "successBody": "Wir melden uns innerhalb von 24 Geschäftsstunden. Sie können uns die Zusammenfassung auch direkt per WhatsApp senden:",
      "successCta": "Zusammenfassung per WhatsApp senden →",
      "errorInvalid": "Ungültige Daten. Bitte prüfen Sie das Formular.",
      "name": "Name *",
      "namePlaceholder": "Ihr Name",
      "company": "Unternehmen (optional)",
      "companyPlaceholder": "Ihr Unternehmen",
      "email": "E-Mail *",
      "emailPlaceholder": "sie@unternehmen.com",
      "whatsapp": "WhatsApp *",
      "whatsappPlaceholder": "+49 151 12345678",
      "country": "Land *",
      "countryPlaceholder": "Deutschland, Schweiz, Österreich...",
      "sectorLabel": "Sektor von Interesse *",
      "sectorPlaceholder": "Sektor auswählen",
      "sectorEnergia": "Energie und Industrialisierung",
      "sectorAgro": "Agroindustrie",
      "sectorTec": "Technologie und digitale Infrastruktur",
      "sectorLog": "Logistik und bioozeanischer Korridor",
      "sectorRealEstate": "Produktive Immobilien",
      "sectorOtro": "Anderes / Sondieren",
      "objectiveLabel": "Ziel *",
      "objectivePlaceholder": "Was suchen Sie?",
      "objInvertir": "Kapital investieren",
      "objInstalar": "Einen Betrieb aufbauen",
      "objSocio": "Lokalen Partner finden",
      "objExportar": "Exportieren / importieren",
      "objExplorar": "Optionen sondieren",
      "capitalLabel": "Kapitalrahmen *",
      "capitalPlaceholder": "Rahmen auswählen",
      "capital1": "Unter 50.000 US$",
      "capital2": "50.000 – 250.000 US$",
      "capital3": "250.000 – 1.000.000 US$",
      "capital4": "Über 1.000.000 US$",
      "capital5": "Keine Angabe",
      "horizonLabel": "Entscheidungshorizont *",
      "horizonPlaceholder": "Wann entscheiden Sie?",
      "horizon1": "0 – 6 Monate",
      "horizon2": "6 – 18 Monate",
      "horizon3": "Über 18 Monate",
      "messageLabel": "Zusätzliche Nachricht (optional)",
      "messagePlaceholder": "Zusätzlicher Kontext, konkrete Fragen, Projektgröße...",
      "submit": "Dossier und Strategiegespräch anfordern →",
      "submitting": "Wird gesendet...",
      "footnote": "Kostenlos. Kein Spam. Antwort innerhalb von 24 Geschäftsstunden."
    },
    "disclaimer": {
      "title": "Rechtlicher Hinweis · Daten vom 10.06.2026",
      "body": "Die Informationen auf dieser Seite dienen Bildungs- und Strategiezwecken. Sie stellen keine Finanz-, Rechts- oder Steuerberatung dar; sie sind kein öffentliches Wertpapierangebot und keine personalisierte Anlageempfehlung. AYCweb vermittelt keine Wertpapiere und verwaltet keine Drittgelder. Jede Investitionsentscheidung erfordert unabhängige Prüfung und eigene professionelle Beratung. Jede Zahl wird mit ihrer Quelle angegeben; Werte können sich im Laufe der Zeit ändern."
    },
    "calc": {
      "kicker": "Energie-Arbitrage-Rechner",
      "title": "Was ist der Betrieb mit paraguayischem Tarif wert?",
      "consumption": "Monatlicher Verbrauch (kWh)",
      "compareAgainst": "Vergleichen mit",
      "advantageTitle": "Vorteil Paraguay",
      "advantageBody": "Bei diesem Verbrauch zeigt Paraguay einen geschätzten Vorteil von <strong>{pct} %</strong> gegenüber der gewählten Referenz.",
      "pyMonth": "Paraguay/Monat",
      "refMonth": "Referenz/Monat",
      "monthlyAdvantage": "Monatlicher Vorteil",
      "annualAdvantage": "Geschätzter Jahresvorteil",
      "cta": "Energie-Analyse anfordern →",
      "bmWorldBusiness": "Weltdurchschnitt Gewerbe",
      "bmWorldResidential": "Weltdurchschnitt Haushalte",
      "bmSouthAmericaBusiness": "Durchschnitt Südamerika Gewerbe",
      "bmEuropeBusiness": "Durchschnitt Europa Gewerbe",
      "bmUsaBusiness": "USA Gewerbe",
      "bmGermanyBusiness": "Deutschland Gewerbe",
      "bmBrazilBusiness": "Brasilien Gewerbe",
      "bmUruguayBusiness": "Uruguay Gewerbe"
    }
  }
} as const;

export type InvertirDict = (typeof INVERTIR_I18N)[InvertirLocale];

export function getInvertirDict(lang: string): InvertirDict {
  return INVERTIR_I18N[(lang in INVERTIR_I18N ? lang : "es") as InvertirLocale];
}
